In [1]:
import pandas as pd
import nltk
from nltk import word_tokenize

In [2]:
sen="the Food was best but Serving was worst"

In [3]:
sen=word_tokenize(sen)

In [4]:
sen

['the', 'Food', 'was', 'best', 'but', 'Serving', 'was', 'worst']

In [5]:
df=pd.DataFrame(sen,columns=['word'])
df['stopword']=0
df['pos_tag']=''

In [6]:
from nltk.corpus import stopwords
a=set(stopwords.words('english'))

In [7]:
df['word_len']=0

In [8]:
df

      word  stopword pos_tag  word_len
0      the         0                 0
1     Food         0                 0
2      was         0                 0
3     best         0                 0
4      but         0                 0
5  Serving         0                 0
6      was         0                 0
7    worst         0                 0

In [9]:
for i in range(0,len(df)):
    if (df['word'][i]) in a:
        df['stopword'][i]=1
        
        
    else:
        df['stopword'][i]=0
        
        
    if(len(df['word'][i])>3):
        df['word_len'][i]=1
    else:
        df['word_len'][i]=0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [10]:
df

      word  stopword pos_tag  word_len
0      the         1                 0
1     Food         0                 1
2      was         1                 0
3     best         0                 1
4      but         1                 0
5  Serving         0                 1
6      was         1                 0
7    worst         0                 1

In [11]:
post_tag=nltk.pos_tag(sen)

In [85]:
post_tag[1][1]

'NNP'

In [79]:
df['pos_tag']=post_tag

ValueError: Length of values does not match length of index

In [80]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,symnet
0,the,1,"(the, DT)",0,Food,,,NNP,0,NULL,0,1,
1,Food,0,"(Food, NNP)",1,was,the,DT,VBD,0,NULL,1,1,
2,was,1,"(was, VBD)",0,best,Food,NNP,JJS,0,NULL,0,2,
3,best,0,"(best, JJS)",1,but,was,VBD,CC,1,NULL,0,1,
4,but,1,"(but, CC)",0,Serving,best,JJS,NNP,0,NULL,0,1,
5,Serving,0,"(Serving, NNP)",1,was,but,CC,VBD,0,NULL,1,1,
6,was,1,"(was, VBD)",0,worst,Serving,NNP,JJS,0,NULL,0,2,
7,worst,0,"(worst, JJS)",1,,was,VBD,,0,NULL,0,1,

In [15]:
next_l=[]
k=0
for i in range(0,len(sen)-1):
    print (i)
    next_l.append(sen[i+1])

0
1
2
3
4
5
6

In [16]:
next_l.append("")

In [17]:
next_l

['Food', 'was', 'best', 'but', 'Serving', 'was', 'worst', '']

In [18]:
df['next_words']=""

In [19]:
df['next_words']=next_l

In [20]:
df['prev_words']=""
prev=[]

In [21]:
prev.append("")

In [22]:
for i in range(1,len(sen)):
    print (i)
    print (sen[i])
    prev.append(sen[i-1])

1
Food
2
was
3
best
4
but
5
Serving
6
was
7
worst

In [23]:
prev

['', 'the', 'Food', 'was', 'best', 'but', 'Serving', 'was']

In [24]:
df['prev_words']=prev

In [25]:
df

      word  stopword         pos_tag  word_len next_words prev_words
0      the         1       (the, DT)         0       Food
1     Food         0     (Food, NNP)         1        was        the
2      was         1      (was, VBD)         0       best       Food
3     best         0     (best, JJS)         1        but        was
4      but         1       (but, CC)         0    Serving       best
5  Serving         0  (Serving, NNP)         1        was        but
6      was         1      (was, VBD)         0      worst    Serving
7    worst         0    (worst, JJS)         1                   was

In [26]:
df['pre_word_tag']=""
df['post_word_tag']=""

In [27]:
import os
a=os.popen("echo '"+"the food was best but serving was worst"+"' > ~/stanford-parser-2012-11-12/stanfordtemp.txt")
parser_out = os.popen("~/stanford-parser-2012-11-12/lexparser.sh ~/stanford-parser-2012-11-12/stanfordtemp.txt")
print (parser_out)
for relation in parser_out:
    print(relation)

<os._wrap_close object at 0x0000027DCD952CF8>

In [28]:
from nltk.tree import Tree

examples = [
    '(ROOT (S (NP (DT the) (NN food)) (VP (VBD was) (NP (NP (JJS best)) (PP (CC but) (S (VP (VBG serving) (SBAR (S (VP (VBD was) (ADJP (JJS worst))))))))))))'
]
head_word=[]

def find_noun_phrases(tree):
    return [subtree for subtree in tree.subtrees(lambda t: t.label()=='NP')]

def find_head_of_np(np):
    noun_tags = ['NN', 'NNS', 'NNP', 'NNPS']
    top_level_trees = [np[i] for i in range(len(np)) if type(np[i]) is Tree]
    ## search for a top-level noun
    top_level_nouns = [t for t in top_level_trees if t.label() in noun_tags]
    if len(top_level_nouns) > 0:
        ## if you find some, pick the rightmost one, just 'cause
        return top_level_nouns[-1][0]
    else:
        ## search for a top-level np
        top_level_nps = [t for t in top_level_trees if t.label()=='NP']
        if len(top_level_nps) > 0:
            ## if you find some, pick the head of the rightmost one, just 'cause
            return find_head_of_np(top_level_nps[-1])
        else:
            ## search for any noun
            nouns = [p[0] for p in np.pos() if p[1] in noun_tags]
            if len(nouns) > 0:
                ## if you find some, pick the rightmost one, just 'cause
                return nouns[-1]
            else:
                ## return the rightmost word, just 'cause
                return np.leaves()[-1]

for example in examples:
    tree = Tree.fromstring(example)
    for np in find_noun_phrases(tree):
       
        print (" ".join(np.leaves()))
        head = find_head_of_np(np)
        
        if head not in head_word:
            
            head_word.append(head)

the food
best but serving was worst
best

In [29]:
head_word

['food', 'best']

In [92]:
post_tag

[('the', 'DT'),
 ('Food', 'NNP'),
 ('was', 'VBD'),
 ('best', 'JJS'),
 ('but', 'CC'),
 ('Serving', 'NNP'),
 ('was', 'VBD'),
 ('worst', 'JJS')]

In [93]:
df['head_word']=0
pos_pre=[]
pos_pre.append("")
pos_post=[]
pos=[]
df['pos']=""

for i in range(0,len(post_tag)-1):
    pos_post.append(post_tag[i+1][1])
pos_post.append("")

for i in range(0,len(post_tag)):
    pos.append(post_tag[i][1])

for i in range(1,len(post_tag)):
    pos_pre.append(post_tag[i-1][1])

df['pre_word_tag']=pos_pre
df['post_word_tag']=pos_post
df['pos']=pos

In [76]:

for i in range(0,len(df)):
   
        

    if (df['word'][i]) in head_word:
        print (df['word'][i])
        df['head_word'][i]=1
    else:
        df['head_word'][i]=0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

best

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,symnet,pos
0,the,1,"(the, DT)",0,Food,,,NNP,0,NULL,0,1,,DT
1,Food,0,"(Food, NNP)",1,was,the,DT,VBD,0,NULL,1,1,,NNP
2,was,1,"(was, VBD)",0,best,Food,NNP,JJS,0,NULL,0,2,,VBD
3,best,0,"(best, JJS)",1,but,was,VBD,CC,0,NULL,0,1,,JJS
4,but,1,"(but, CC)",0,Serving,best,JJS,NNP,0,NULL,0,1,,CC
5,Serving,0,"(Serving, NNP)",1,was,but,CC,VBD,0,NULL,1,1,,NNP
6,was,1,"(was, VBD)",0,worst,Serving,NNP,JJS,0,NULL,0,2,,VBD
7,worst,0,"(worst, JJS)",1,,was,VBD,,0,NULL,0,1,,JJS

In [78]:
t1="she is serving food in the restaurant"
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
  
    print(lemmatizer.lemmatize('better','r'))

well
well
well
well
well
well
well
well

In [41]:
from nltk.corpus import wordnet

morphy_tag = {'NN':wordnet.NOUN,'JJS':wordnet.ADJ,'VBD':wordnet.VERB,'RBS':wordnet.ADV,'VBG':wordnet.VERB}

In [42]:
morphy_tag

{'NN': 'n', 'JJS': 'a', 'VBD': 'v', 'RBS': 'r', 'VBG': 'v'}

In [43]:
t1="she is serving food in the restaurant"
df['lematized_words']='NULL'
lema=[]
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
    c=post_tag[i][1]
    for name in morphy_tag.keys():
        if name == c:
            print (name)
            new=morphy_tag[name]
            print (new)
    lema.append(lemmatizer.lemmatize(post_tag[i][0],new))

NameError: name 'new' is not defined

In [44]:
lema

[]

In [45]:
df['lematized_words']=lema

ValueError: Length of values does not match length of index

In [46]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",0,NULL
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",0,NULL
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",0,NULL
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",1,NULL
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",0,NULL
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",0,NULL
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",0,NULL
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,0,NULL

In [47]:
df['ortho_features']=''

In [48]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",0,NULL,
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",0,NULL,
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",0,NULL,
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",1,NULL,
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",0,NULL,
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",0,NULL,
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",0,NULL,
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,0,NULL,

In [49]:
for i in range(0,len(df)):
    if ((df['word'][i].istitle() == True) or (df['word'][i].isdigit()==True)):
        df['ortho_features'][i]=1
    else:
        df['ortho_features'][i]=0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [50]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",0,NULL,0
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",0,NULL,1
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",0,NULL,0
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",1,NULL,0
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",0,NULL,0
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",0,NULL,1
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",0,NULL,0
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,0,NULL,0

In [51]:
df['token_freq']=''

In [52]:
for i in range(0,len(df)):
    df['token_freq'][i]=sen.count(df['word'][i])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [53]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",0,NULL,0,1
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",0,NULL,1,1
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",0,NULL,0,2
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",1,NULL,0,1
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",0,NULL,0,1
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",0,NULL,1,1
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",0,NULL,0,2
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,0,NULL,0,1

In [54]:
df['symnet']=''

In [55]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,symnet
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",0,NULL,0,1,
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",0,NULL,1,1,
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",0,NULL,0,2,
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",1,NULL,0,1,
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",0,NULL,0,1,
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",0,NULL,1,1,
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",0,NULL,0,2,
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,0,NULL,0,1,

In [100]:
from nltk.corpus import wordnet
synonyms=[]
for i in range(0,len(df)):
    for syn in wordnet.synsets((df['word'][i])):
        for l in syn.lemmas():
            print(l.name())
            synonyms.append(l.name())
        print("\n")

food
nutrient


food
solid_food


food
food_for_thought
intellectual_nourishment


Washington
Evergreen_State
WA


be


be


be


exist
be


be


equal
be


constitute
represent
make_up
comprise
be


be
follow


embody
be
personify


be


be
live


be


cost
be


best


best
topper


Best
C._H._Best
Charles_Herbert_Best


outdo
outflank
trump
best
scoop


best


better
best


good


full
good


good


estimable
good
honorable
respectable


beneficial
good


good


good
just
upright


adept
expert
good
practiced
proficient
skillful
skilful


good


dear
good
near


dependable
good
safe
secure


good
right
ripe


good
well


effective
good
in_effect
in_force


good


good
serious


good
sound


good
salutary


good
honest


good
undecomposed
unspoiled
unspoilt


good


best


best


better
best


well
good


well


well
easily


well


well


well


well
considerably
substantially


well
intimately


well


well


well
advantageously


well
comfortably


well


merely
simply
just
only
but


helping
portion
serving


service
serving
service_of_process


serve
function


serve


serve


service
serve


serve
help


serve
serve_up
dish_out
dish_up
dish


serve


serve
serve_well


serve
do


serve
attend_to
wait_on
attend
assist


serve
process
swear_out


suffice
do
answer
serve


serve


serve
service


serve


Washington
Evergreen_State
WA


be


be


be


exist
be


be


equal
be


constitute
represent
make_up
comprise
be


be
follow


embody
be
personify


be


be
live


be


cost
be


worst


worst


worst


worst
pip
mop_up
whip
rack_up


worst


bad


bad
big


bad
tough


bad
spoiled
spoilt


regretful
sorry
bad


bad
uncollectible


bad


bad


bad
risky
high-risk
speculative


bad
unfit
unsound


bad


bad


bad
forged


bad
defective


worst

In [57]:
print(synonyms)

['food', 'nutrient', 'food', 'solid_food', 'food', 'food_for_thought', 'intellectual_nourishment', 'Washington', 'Evergreen_State', 'WA', 'be', 'be', 'be', 'exist', 'be', 'be', 'equal', 'be', 'constitute', 'represent', 'make_up', 'comprise', 'be', 'be', 'follow', 'embody', 'be', 'personify', 'be', 'be', 'live', 'be', 'cost', 'be', 'best', 'best', 'topper', 'Best', 'C._H._Best', 'Charles_Herbert_Best', 'outdo', 'outflank', 'trump', 'best', 'scoop', 'best', 'better', 'best', 'good', 'full', 'good', 'good', 'estimable', 'good', 'honorable', 'respectable', 'beneficial', 'good', 'good', 'good', 'just', 'upright', 'adept', 'expert', 'good', 'practiced', 'proficient', 'skillful', 'skilful', 'good', 'dear', 'good', 'near', 'dependable', 'good', 'safe', 'secure', 'good', 'right', 'ripe', 'good', 'well', 'effective', 'good', 'in_effect', 'in_force', 'good', 'good', 'serious', 'good', 'sound', 'good', 'salutary', 'good', 'honest', 'good', 'undecomposed', 'unspoiled', 'unspoilt', 'good', 'best', 'best', 'better', 'best', 'well', 'good', 'well', 'well', 'easily', 'well', 'well', 'well', 'well', 'considerably', 'substantially', 'well', 'intimately', 'well', 'well', 'well', 'advantageously', 'well', 'comfortably', 'well', 'merely', 'simply', 'just', 'only', 'but', 'helping', 'portion', 'serving', 'service', 'serving', 'service_of_process', 'serve', 'function', 'serve', 'serve', 'service', 'serve', 'serve', 'help', 'serve', 'serve_up', 'dish_out', 'dish_up', 'dish', 'serve', 'serve', 'serve_well', 'serve', 'do', 'serve', 'attend_to', 'wait_on', 'attend', 'assist', 'serve', 'process', 'swear_out', 'suffice', 'do', 'answer', 'serve', 'serve', 'serve', 'service', 'serve', 'Washington', 'Evergreen_State', 'WA', 'be', 'be', 'be', 'exist', 'be', 'be', 'equal', 'be', 'constitute', 'represent', 'make_up', 'comprise', 'be', 'be', 'follow', 'embody', 'be', 'personify', 'be', 'be', 'live', 'be', 'cost', 'be', 'worst', 'worst', 'worst', 'worst', 'pip', 'mop_up', 'whip', 'rack_up', 'worst', 'bad', 'bad', 'big', 'bad', 'tough', 'bad', 'spoiled', 'spoilt', 'regretful', 'sorry', 'bad', 'bad', 'uncollectible', 'bad', 'bad', 'bad', 'risky', 'high-risk', 'speculative', 'bad', 'unfit', 'unsound', 'bad', 'bad', 'bad', 'forged', 'bad', 'defective', 'worst']

In [ ]:
df['named_entity']=''

In [ ]:
import nltk



parse_tree = nltk.ne_chunk(nltk.tag.pos_tag(sen.split()), binary=True)  # POS tagging before chunking!

named_entities = []

for t in parse_tree.subtrees():
    if t.label() == 'NE':
        named_entities.append(t)
        # named_entities.append(list(t))  # if you want to save a list of tagged words instead of a tree

print(named_entities)

In [ ]:

import xml.etree.ElementTree as ET
import nltk

def get_list(path):
    tree=ET.parse(path)
    root = tree.getroot()
    text_list = []
    id_list=[]
    new_list=[]
    sentences_list=[]
    opinion_list = []
    for review in root.findall('Review'):
        text_string=""
        opinion_inner_list=[]
        for sent in review.findall('./sentences/sentence'):
            ids=sent.attrib['id']
            id_list.append(ids)
            text_string= text_string+ " "+ sent.find('text').text
            new_list.append(ids)
            sentences_list.append(sent.find('text').text)
            new_list.append(sent.find('text').text)
        
        text_list.append(text_string)
        for opinion in review.findall('./Opinions/Opinion'):
            opinion_dict = {
                opinion.get('category').replace('#','_'): opinion.get('polarity')
            }
            opinion_inner_list.append(opinion_dict)
        opinion_list.append(opinion_inner_list)
    return text_list,opinion_list,new_list,sentences_list
train_text_list,train_opinion_list,new_list,sentences_list = get_list("C:/Users/user/Downloads/ABSA16_Laptops_Train_English_SB2.xml")

In [ ]:
sentences_list

In [ ]:
fp = open('parser_sentences_new.csv','w')

for each_sentence in sentences_list:
    print (each_sentence)
    fp.write("%s\n" %each_sentence)
    
        #fp.write('\n')
fp.close()

In [60]:
wordnet.synsets('food')

[Synset('food.n.01'), Synset('food.n.02'), Synset('food.n.03')]

In [63]:
from sklearn.preprocessing import LabelEncoder
class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self # not relevant here

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

In [71]:
MultiColumnLabelEncoder(columns = ['word','pos_tag','next_words']).fit_transform(df)

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,symnet
0,4,1,4,0,1,,,"(Food, NNP)",0,NULL,0,1,
1,0,0,0,1,5,the,"(the, DT)","(was, VBD)",0,NULL,1,1,
2,5,1,5,0,3,Food,"(Food, NNP)","(best, JJS)",0,NULL,0,2,
3,2,0,2,1,4,was,"(was, VBD)","(but, CC)",1,NULL,0,1,
4,3,1,3,0,2,best,"(best, JJS)","(Serving, NNP)",0,NULL,0,1,
5,1,0,1,1,5,but,"(but, CC)","(was, VBD)",0,NULL,1,1,
6,5,1,5,0,6,Serving,"(Serving, NNP)","(worst, JJS)",0,NULL,0,2,
7,6,0,6,1,0,was,"(was, VBD)",,0,NULL,0,1,

In [70]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,symnet
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",0,NULL,0,1,
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",0,NULL,1,1,
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",0,NULL,0,2,
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",1,NULL,0,1,
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",0,NULL,0,1,
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",0,NULL,1,1,
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",0,NULL,0,2,
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,0,NULL,0,1,