In [1]:
import pandas as pd
import nltk
from nltk import word_tokenize

In [139]:
sen="the Food was best but Serving was worst"

In [140]:
sen=word_tokenize(sen)

In [62]:
sen

['the', 'Food', 'was', 'best', 'but', 'Serving', 'was', 'worst']

In [63]:
df=pd.DataFrame(sen,columns=['word'])
df['stopword']=0
df['pos_tag']=''

In [64]:
from nltk.corpus import stopwords
a=set(stopwords.words('english'))

In [65]:
df['word_len']=0

In [66]:
df

      word  stopword pos_tag  word_len
0      the         0                 0
1     Food         0                 0
2      was         0                 0
3     best         0                 0
4      but         0                 0
5  Serving         0                 0
6      was         0                 0
7    worst         0                 0

In [67]:
for i in range(0,len(df)):
    if (df['word'][i]) in a:
        df['stopword'][i]=1
        
        
    else:
        df['stopword'][i]=0
        
        
    if(len(df['word'][i])>3):
        df['word_len'][i]=1
    else:
        df['word_len'][i]=0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [68]:
df

      word  stopword pos_tag  word_len
0      the         1                 0
1     Food         0                 1
2      was         1                 0
3     best         0                 1
4      but         1                 0
5  Serving         0                 1
6      was         1                 0
7    worst         0                 1

In [69]:
post_tag=nltk.pos_tag(sen
                     )

In [70]:
post_tag[0][1]

'DT'

In [71]:
df['pos_tag']=post_tag

In [72]:
df

      word  stopword         pos_tag  word_len
0      the         1       (the, DT)         0
1     Food         0     (Food, NNP)         1
2      was         1      (was, VBD)         0
3     best         0     (best, JJS)         1
4      but         1       (but, CC)         0
5  Serving         0  (Serving, NNP)         1
6      was         1      (was, VBD)         0
7    worst         0    (worst, JJS)         1

In [73]:
next_l=[]
k=0
for i in range(0,len(sen)-1):
    print (i)
    next_l.append(sen[i+1])

0
1
2
3
4
5
6

In [74]:
next_l.append("")

In [75]:
next_l

['Food', 'was', 'best', 'but', 'Serving', 'was', 'worst', '']

In [76]:
df['next_words']=""

In [77]:
df['next_words']=next_l

In [78]:
df['prev_words']=""
prev=[]

In [79]:
prev.append("")

In [80]:
for i in range(1,len(sen)):
    print (i)
    print (sen[i])
    prev.append(sen[i-1])

1
Food
2
was
3
best
4
but
5
Serving
6
was
7
worst

In [81]:
prev

['', 'the', 'Food', 'was', 'best', 'but', 'Serving', 'was']

In [82]:
df['prev_words']=prev

In [83]:
df

      word  stopword         pos_tag  word_len next_words prev_words
0      the         1       (the, DT)         0       Food
1     Food         0     (Food, NNP)         1        was        the
2      was         1      (was, VBD)         0       best       Food
3     best         0     (best, JJS)         1        but        was
4      but         1       (but, CC)         0    Serving       best
5  Serving         0  (Serving, NNP)         1        was        but
6      was         1      (was, VBD)         0      worst    Serving
7    worst         0    (worst, JJS)         1                   was

In [84]:
df['pre_word_tag']=""
df['post_word_tag']=""

In [96]:
import os
a=os.popen("echo '"+"the food was best but serving was worst"+"' > ~/stanford-parser-2012-11-12/stanfordtemp.txt")
parser_out = os.popen("~/stanford-parser-2012-11-12/lexparser.sh ~/stanford-parser-2012-11-12/stanfordtemp.txt")
print (parser_out)
for relation in parser_out:
    print(relation)

<os._wrap_close object at 0x0000019CAA495550>

In [97]:
from nltk.tree import Tree

examples = [
    '(ROOT (S (NP (DT the) (NN food)) (VP (VBD was) (NP (NP (JJS best)) (PP (CC but) (S (VP (VBG serving) (SBAR (S (VP (VBD was) (ADJP (JJS worst))))))))))))'
]
head_word=[]

def find_noun_phrases(tree):
    return [subtree for subtree in tree.subtrees(lambda t: t.label()=='NP')]

def find_head_of_np(np):
    noun_tags = ['NN', 'NNS', 'NNP', 'NNPS']
    top_level_trees = [np[i] for i in range(len(np)) if type(np[i]) is Tree]
    ## search for a top-level noun
    top_level_nouns = [t for t in top_level_trees if t.label() in noun_tags]
    if len(top_level_nouns) > 0:
        ## if you find some, pick the rightmost one, just 'cause
        return top_level_nouns[-1][0]
    else:
        ## search for a top-level np
        top_level_nps = [t for t in top_level_trees if t.label()=='NP']
        if len(top_level_nps) > 0:
            ## if you find some, pick the head of the rightmost one, just 'cause
            return find_head_of_np(top_level_nps[-1])
        else:
            ## search for any noun
            nouns = [p[0] for p in np.pos() if p[1] in noun_tags]
            if len(nouns) > 0:
                ## if you find some, pick the rightmost one, just 'cause
                return nouns[-1]
            else:
                ## return the rightmost word, just 'cause
                return np.leaves()[-1]

for example in examples:
    tree = Tree.fromstring(example)
    for np in find_noun_phrases(tree):
       
        print (" ".join(np.leaves()))
        head = find_head_of_np(np)
        
        if head not in head_word:
            
            head_word.append(head)

the food
best but serving was worst
best

In [98]:
head_word

['food', 'best']

In [99]:
post_tag[0]

('the', 'DT')

In [100]:
df['head_word']=0
pos_pre=[]
pos_pre.append("")
pos_post=[]
for i in range(0,len(post_tag)-1):
    pos_post.append(post_tag[i+1])
pos_post.append("")

for i in range(1,len(post_tag)):
    pos_pre.append(post_tag[i-1])

df['pre_word_tag']=pos_pre
df['post_word_tag']=pos_post

In [101]:

for i in range(0,len(df)):
   
        

    if (df['word'][i]) in head_word:
        print (df['word'][i])
        df['head_word'][i]=1
    else:
        df['head_word'][i]=0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

best

In [102]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,lematized_words,ortho_features,head_word
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",NULL,,0
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",NULL,,0
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",NULL,,0
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",NULL,,1
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",NULL,,0
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",NULL,,0
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",NULL,,0
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,NULL,,0

In [103]:
t1="she is serving food in the restaurant"
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
  
    print(lemmatizer.lemmatize('better','r'))

well
well
well
well
well
well
well
well

In [104]:
from nltk.corpus import wordnet

morphy_tag = {'NN':wordnet.NOUN,'JJS':wordnet.ADJ,'VBD':wordnet.VERB,'RBS':wordnet.ADV,'VBG':wordnet.VERB}

In [105]:
morphy_tag

{'NN': 'n', 'JJS': 'a', 'VBD': 'v', 'RBS': 'r', 'VBG': 'v'}

In [106]:
t1="she is serving food in the restaurant"
df['lematized_words']='NULL'
lema=[]
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
    c=post_tag[i][1]
    for name in morphy_tag.keys():
        if name == c:
            print (name)
            new=morphy_tag[name]
            print (new)
    lema.append(lemmatizer.lemmatize(post_tag[i][0],new))

NameError: name 'new' is not defined

In [107]:
lema

[]

In [108]:
df['lematized_words']=lema

ValueError: Length of values does not match length of index

In [109]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,lematized_words,ortho_features,head_word
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",NULL,,0
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",NULL,,0
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",NULL,,0
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",NULL,,1
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",NULL,,0
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",NULL,,0
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",NULL,,0
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,NULL,,0

In [110]:
df['ortho_features']=''

In [136]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,lematized_words,ortho_features,head_word
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",NULL,,0
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",NULL,1,0
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",NULL,,0
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",NULL,,1
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",NULL,,0
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",NULL,1,0
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",NULL,,0
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,NULL,,0

In [150]:
for i in range(0,len(df)):
    if ((df['word'][i].istitle() == True) or (df['word'][i].isdigit()==True)):
        df['ortho_features'][i]=1
    else:
        df['ortho_features'][i]=0

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [151]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,lematized_words,ortho_features,head_word
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",NULL,0,0
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",NULL,1,0
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",NULL,0,0
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",NULL,0,1
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",NULL,0,0
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",NULL,1,0
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",NULL,0,0
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,NULL,0,0

In [164]:
df['token_freq']=''

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,lematized_words,ortho_features,head_word,token_freq
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",NULL,0,0,
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",NULL,1,0,
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",NULL,0,0,
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",NULL,0,1,
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",NULL,0,0,
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",NULL,1,0,
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",NULL,0,0,
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,NULL,0,0,

In [166]:
for i in range(0,len(df)):
    df['token_freq'][i]=sen.count(df['word'][i])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [167]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,lematized_words,ortho_features,head_word,token_freq
0,the,1,"(the, DT)",0,Food,,,"(Food, NNP)",NULL,0,0,1
1,Food,0,"(Food, NNP)",1,was,the,"(the, DT)","(was, VBD)",NULL,1,0,1
2,was,1,"(was, VBD)",0,best,Food,"(Food, NNP)","(best, JJS)",NULL,0,0,2
3,best,0,"(best, JJS)",1,but,was,"(was, VBD)","(but, CC)",NULL,0,1,1
4,but,1,"(but, CC)",0,Serving,best,"(best, JJS)","(Serving, NNP)",NULL,0,0,1
5,Serving,0,"(Serving, NNP)",1,was,but,"(but, CC)","(was, VBD)",NULL,1,0,1
6,was,1,"(was, VBD)",0,worst,Serving,"(Serving, NNP)","(worst, JJS)",NULL,0,0,2
7,worst,0,"(worst, JJS)",1,,was,"(was, VBD)",,NULL,0,0,1